---
output: html_document
---


```{r warning=FALSE,error=FALSE,message=FALSE}
install.packages("twitterR",repos ="http://cran.us.r-project.org")
install.packages("snowballC",repos ="http://cran.us.r-project.org")
install.packages("ROAuth",repos ="http://cran.us.r-project.org")
install.packages("RCurl",repos ="http://cran.us.r-project.org")
install.packages("tm",repos ="http://cran.us.r-project.org")
install.packages("wordcloud",repos ="http://cran.us.r-project.org")
library(SnowballC)
library(twitteR)
library(ROAuth)
library(RCurl)
library(tm)
library(wordcloud)
```
#twitter authentication
```{r echo=FALSE}
consumerKey <- "tT7e2vSIAv8mzOFjKnedhau0D"
consumerSecret <- "PWgfDoG24U7VUiFCHnLarNz0RmQbjPEofywxxOHcp1eOI6dotI"
accessToken <- "2608779027-8NQT6mu3Kf8hwKZTAuPr9ua3wpS43cs02UqeMWZ"
accessTokenSecret <- "V3jfYIVnbztp9OlbLlDUOTz2bRNJrOMBLe3D3Old6JVpb"
```
```{r}
twitteR::setup_twitter_oauth(consumerKey,consumerSecret,accessToken,accessTokenSecret)

```

#retrives tweet from twitter
```{r}
tweets=searchTwitter("machine+learning",lang = "en",n=1200,resultType = "recent")
class(tweets)
head(tweets)
```
#converting list to vector
```{r}
tweets_text=sapply(tweets,function(x) x$getText())
str(tweets_text)
```
#creates corpus from vector of tweets
```{r}
tweets_corpus=Corpus(VectorSource(tweets_text))
```
*if you get the below error*
*In mclapply(content(x), FUN, ...) :*
*all scheduled cores encountered errors in user code*
*run this step if you get the error:*

```{r}
tweets_corpus <- tm_map(tweets_corpus,
                   content_transformer(function(x) iconv(x, to='UTF-8-MAC', sub='byte')),
                   mc.cores=1)
inspect(tweets_corpus[100])
```
#cleaning

```{r}
tweets_clean=tm_map(tweets_corpus,removePunctuation,lazy = TRUE)
tweets_clean=tm_map(tweets_clean,content_transformer(tolower),lazy = T)
tweets_clean=tm_map(tweets_clean,removeWords,stopwords("english"),lazy = T)
tweets_clean=tm_map(tweets_clean,removeNumbers,lazy = T)
tweets_clean=tm_map(tweets_clean,stripWhitespace,lazy = T)
tweets_clean=tm_map(tweets_clean,removeWords,c("machine","learning"),lazy = T)
```
#wordcloud play with parameters
```{r warning=FALSE,message=FALSE}
wordcloud(tweets_clean,random.order = F, colors = rainbow(50))

```


